version: "2"
services:
    camac_cache:
        image: memcached
        ports:
            - "11211:11211"

    camac_db:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_PASSWORD=camac
            - POSTGRES_USER=camac
            - POSTGRES_DB=camac

    camac_django:
        build: django
        ports:
          - '8000:80'
        volumes:
          - ./django:/app
          - ./tools:/tools
        depends_on:
          - camac_db
          - camac_cache
        environment:
          - ENV=docker
          - DJANGO_DATABASE_HOST=camac_db
          - DJANGO_CACHE_LOCATION=camac_cache:11211
        command: /tools/wait-for-it.sh camac_db:5432 --timeout=60 -- uwsgi
